Fix typos
touchlab/KMMBridge pull request #227
Opened 2023-09-14 13:11 UTC by findjigar

2023-09-18 18:52 UTC, samhill303 requested changes

2023-09-18 18:52 UTC, samhill303 commented on website/docs/DEFAULT_GITHUB_FLOW.md
>  These steps are needed for any private artifact hosting, but won't be necessary if your artifacts are hosted somewhere publicly accessible.
This note block can be removed

2023-09-18 18:52 UTC, samhill303 commented on website/docs/DEFAULT_GITHUB_FLOW.md
> +If you're using the github packages for artifact hosting via `addGithubPackagesRepository()`, accessing the artifacts requires authentication. You'll need to tell the local machine how to access the
```suggestion
If you're using the github packages for artifact hosting via `addGithubPackagesRepository()`, accessing the artifacts requires authentication. You can do this either by editing the `~/.netrc` file, or by adding the info to your local keychain.
```

2023-09-18 19:26 UTC, findjigar commented on website/docs/DEFAULT_GITHUB_FLOW.md
>  These steps are needed for any private artifact hosting, but won't be necessary if your artifacts are hosted somewhere publicly accessible.
This block
> These steps are needed for any private artifact hosting, but won't be necessary if your artifacts are hosted somewhere publicly accessible.

I feel like it's for accessing the artifacts via Xcode, and it might still be true that one don't need any steps for accessing publicly accessible artifacts?

2023-09-18 20:04 UTC, findjigar commented
@samhill303 PR updated

2023-09-19 13:12 UTC, samhill303 approved these changes

2023-09-19 13:29 UTC, merged